// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuvqdivqzcoqttyidlew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1dnFkaXZxemNvcXR0eWlkbGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MDI1MTQsImV4cCI6MjA3ODE3ODUxNH0.y21o9YBckGs0c4f-nvK4vRdXfQE-VWJA-9JUkNKcH28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});